### ISSUE TITLE
关于端口设置

### ISSUE THREAD

**Issue by FiredRice** [nicepkg/gpt-runner#11]
vscode上gpt-runner启动后会占用3001端口，很容易影响很多项目的启动。
可否增加用户自己选择端口的设置项，或者将端口换一个冷门的

**Comment by 2214962083** [comment]
你好，gpt-runner会自动寻找可用端口，不是固定3001

**Comment by FiredRice** [comment]
这样啊。但是插件基本都会先于项目启动，抢占端口的概率还是挺高的。我这两天体验下来都遇到这种情况了。希望能优化一下这方面的体验

**Comment by 2214962083** [comment]
> 这样啊。但是插件基本都会先于项目启动，抢占端口的概率还是挺高的。我这两天体验下来都遇到这种情况了。希望能优化一下这方面的体验

了解，由于不同项目需需要启动不同的 gpt-runner 实例，写死端口会导致无法创建多个实例，所以我会在下一版加上排除端口配置，你可以配置要排除的端口， gpt-runner永远不会使用那个端口

**Comment by 2214962083** [comment]
@FiredRice 

GPT-Runner v1.1.2 允许设置排除端口了，重启 vscode 即可更新。

<img width="886" alt="WechatIMG319" src="https://github.com/nicepkg/gpt-runner/assets/35005637/8fd27a1f-9c41-44c6-ad18-7f151edd062f">
