### ISSUE TITLE
confirm failed

### ISSUE THREAD

**Issue by BillAmihom** [nicepkg/gpt-runner#12]
![image](https://github.com/nicepkg/gpt-runner/assets/72117813/ea5e929f-8f60-427f-ba2b-dfb8dd32dfd9)
一开始点confirm就报错了，请问这个怎么弄呢？

**Comment by BillAmihom** [comment]
似乎是网络问题，要给服务器翻墙

**Comment by 2214962083** [comment]
架梯子

**Comment by 2214962083** [comment]
从 v1.2.6 版本开始，这个问题应该被修复了
