### ISSUE TITLE
gpt-runner-web build fails

### ISSUE THREAD

**Issue by CogNetSys** [nicepkg/gpt-runner#14]
Forked repository, cloned repo, changed directory and ran "pnpm install" but it fails the "postinstall: pnpm build" with an error.

![Screenshot from 2023-08-11 10-58-02-1](https://github.com/nicepkg/gpt-runner/assets/90477669/af82e613-8d86-4af5-a8ea-4d19fcfe5fca)

**Comment by CogNetSys** [comment]
It is the latest: 1.2.5 version I cloned.

**Comment by CogNetSys** [comment]
Im on Ubuntu 22 @2214962083

**Comment by 2214962083** [comment]
`git pull` and run `pnpm i` again, the error reason is not in screenshot. can you give me the fullscreen shot

**Comment by CogNetSys** [comment]
I was able to resolve the issue; it was on my end. I apologize.

**Comment by 2214962083** [comment]
no worry, feel free
