### ISSUE TITLE
Feature Request: Accessibility

### ISSUE THREAD

**Issue by CogNetSys** [nicepkg/gpt-runner#17]
Accessibility for those with disabilities is something I take very, very serious and would like to completely comb through every aspect of GPT-Runner to ensure it is fully accessible. Tab indexes, alternate text, keyboard shortcuts, etc. Im open to discussion on this topic and interested in your recommendations to establish a reasonable plan. gpt-runner-web will be much easier for me than the others.

**Comment by 2214962083** [comment]
Your proposal is excellent. In fact, my experience with Accessibility is quite limited, and I am not very proficient in this area. I would highly appreciate if you could submit a PR regarding this.

@CogNetSys
