### ISSUE TITLE
文件选中可能存在问题

### ISSUE THREAD

**Issue by evanhon0110** [nicepkg/gpt-runner#18]
有时候选中了文件，但是GPT却说无法看见，实际未将文件内容携带上
gpt runner：1.2.6
vs code：1.81.1
node：16.17.1

**Comment by 2214962083** [comment]
这可能是第三方api供应商转发的问题，你可以勾选这个选项
<img width="534" alt="image" src="https://github.com/nicepkg/gpt-runner/assets/35005637/5cbb3e36-410e-4665-84c5-de9e969d56c8">

**Comment by evanhon0110** [comment]
感谢
