### ISSUE TITLE
终端执行`npx gptr`出现“'gptr' 不是内部或外部命令，也不是可运行的程序 或批处理文件。”是什么原因？

### ISSUE THREAD

**Issue by oLd-Y** [nicepkg/gpt-runner#6]
我想在IDEA中使用，我用的是nvm管理nodejs版本，可以正常显示nodejs：
![image](https://github.com/nicepkg/gpt-runner/assets/71266297/0f00653c-92c2-4c3d-89e4-8d053d49fe5a)
但是执行`npx gptr`就会报错：
![image](https://github.com/nicepkg/gpt-runner/assets/71266297/4cc0ba0f-7915-46b8-9041-fa6638fb989c)
也不知道如何将`gptr`添加到环境变量里面，大佬求解。

**Comment by 2214962083** [comment]
试试npm i -g gptr全局安装gptr然后执行gptr

**Comment by oLd-Y** [comment]
启动了，谢谢大佬
