### ISSUE TITLE
[BUG] 无法检测到 xxx.gpt.md

### ISSUE THREAD

**Issue by Mingzefei** [nicepkg/gpt-runner#8]
vscode 插件，v1.0

1. 第一次运行时已使用插件自动创建 `/gpt-runner/copilot.gpt.md` 文件，但再次打开时依然提示 `there is no xxx.gpt.md file in the current directory`。
2. 创建 copilot.gpt.md 耗时极长。

**Comment by 2214962083** [comment]
请更新 vscode 到最新版，打开一个小项目，排除一下问题。

**Comment by 2214962083** [comment]
> 但再次打开时依然提示 there is no xxx.gpt.md file in the current directory。

你指的是一闪而过的提示还是一直提示？

> 创建 copilot.gpt.md 耗时极长。

这个有超过2秒吗

**Comment by Mingzefei** [comment]
> 请更新 vscode 到最新版，打开一个小项目，排除一下问题。

vscode 已更新到最新版，使用小项目测试（共10个文件）。

**Comment by Mingzefei** [comment]
> > 但再次打开时依然提示 there is no xxx.gpt.md file in the current directory。
> 
> 你指的是一闪而过的提示还是一直提示？
> 
> > 创建 copilot.gpt.md 耗时极长。
> 
> 这个有超过2秒吗

一直显示，远超2秒。
![image](https://github.com/nicepkg/gpt-runner/assets/92701892/51128f84-37ab-4db8-bae0-b1e10ba34712)

**Comment by Mingzefei** [comment]
我是在 WSL2 中使用vscode，是否和这个有关？

**Comment by 2214962083** [comment]
是的，wsl2本身的文件操作有延迟，wsl2的性能并不高

**Comment by Mingzefei** [comment]
我在web端创建时收到如下信息，似乎是权限问题，而非性能问题？
![image](https://github.com/nicepkg/gpt-runner/assets/92701892/66e4b134-1e43-4dac-8f7b-fef1a41b4bf2)

**Comment by 2214962083** [comment]
你好，这是由于 server local ip 对不上。这是一个 wsl 引起的问题，就好像你在 vmware 开一个 localhost:3000 服务，你在宿主机打开 localhost:3000 是访问不到的，除非你懂得网络桥接之类的。

我推荐你用 windows 自身的环境安装试试看，有时间我再考虑适配 wsl。

**Comment by Mingzefei** [comment]
我刚才在 windows 下测试，使用vscode插件遇到了完全相同的问题，无法快速创建 gpt.md 文件。
在哪里可以调出该插件的运行日志？这可能对排除有帮助。

**Comment by 2214962083** [comment]
> 我刚才在 windows 下测试，使用vscode插件遇到了完全相同的问题，无法快速创建 gpt.md 文件。 在哪里可以调出该插件的运行日志？这可能对排除有帮助。

<img width="749" alt="image" src="https://github.com/nicepkg/gpt-runner/assets/35005637/14545b87-657f-491b-a739-d5888d81f2e0">

**Comment by Mingzefei** [comment]
我看到了一些报错，但不确定是否有用。
环境：windows，vscode 插件。
![image](https://github.com/nicepkg/gpt-runner/assets/92701892/1cc996de-7121-4348-bb19-831b3b32d925)
这些已经超出我的知识范围，如果需要其他信息请指导我操作。

**Comment by 2214962083** [comment]
> 我看到了一些报错，但不确定是否有用。 环境：windows，vscode 插件。 ![image](https://user-images.githubusercontent.com/92701892/253851473-1cc996de-7121-4348-bb19-831b3b32d925.png) 这些已经超出我的知识范围，如果需要其他信息请指导我操作。

你好，这个错误信息无关，如果你有空的话，可以加我 wechat：qq2214962083，我晚上下班 8 点 30 到家帮你远程调试。

**Comment by mzywl** [comment]
无法写入文件"c:\Users\14116\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-74f6148eb9ea00507ec113ec51c489d6ffb4b771.exe.tmp"(Error: net::ERR_CONNECTION_RESET)

**Comment by 2214962083** [comment]
> 无法写入文件"c:\Users\14116\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-stable-74f6148eb9ea00507ec113ec51c489d6ffb4b771.exe.tmp"(Error: net::ERR_CONNECTION_RESET)

你这个看起来是 vscode 更新问题，不是 gpt-runner 的问题

**Comment by 2214962083** [comment]
远程debug总结：

localhost 域名解析有问题，没指向 127.0.0.1

**Comment by cfx2020** [comment]
在vscode里可以正常使用，在web页面就报错识别不到gpt.md文件，也无法创建，提示typeerror。![image](https://github.com/nicepkg/gpt-runner/assets/60496874/4432167d-8de9-4b16-bc36-2e8080227bae)

![image](https://github.com/nicepkg/gpt-runner/assets/60496874/f910f6be-5036-4921-8385-3df6395192ae)

**Comment by 2214962083** [comment]
@cfx2020 重启vscode，再重新在vscode打开web还会这样吗

**Comment by cfx2020** [comment]
> @cfx2020 重启vscode，再重新在vscode打开web还会这样吗

还是会的，我没有用虚拟机，就是正常的win环境的vscode，因为一开始报node版本低，我就去微软商店升级了一下，全程挂着代理，每次点在浏览器打开都会弹这个fetch failed

**Comment by 2214962083** [comment]
@cfx2020 
加我 wechat： qq2214962083
我帮你远程 debug
