### ISSUE TITLE
UI 上的按钮看不清

### ISSUE THREAD

**Issue by julee** [nicepkg/gpt-runner#9]
<img width="290" alt="image" src="https://github.com/nicepkg/gpt-runner/assets/1493342/cd78777e-f8f9-436a-a12a-87a09324c0a8">

**Comment by 2214962083** [comment]
## 设置一下主题

<img width="530" alt="image" src="https://github.com/nicepkg/gpt-runner/assets/35005637/c76e2a98-0030-4245-9ffd-97c675bf0aca">
